"""
System 2 Configuration
======================

Central source of truth for:
  - Behavioral feature definitions (15 features, voice + SMS excluded)
  - Population norms (healthy mean/std from StudentLife + literature)
  - Disorder prototype vectors — Frame 1 (absolute) & Frame 2 (z-scores)
  - Feature diagnostic weights
  - Confidence thresholds
  - Temporal shape detection parameters & compatibility matrix
"""

from __future__ import annotations

import json
import pathlib
from typing import Dict, List

# ── Path helpers ─────────────────────────────────────────────────────────
_THIS_DIR = pathlib.Path(__file__).resolve().parent
_DATA_DIR = _THIS_DIR.parent / "data"

# ── 1. Behavioral Feature Set (30 clinical and telemetry features) ───────
BEHAVIORAL_FEATURES: List[str] = [
    "screen_time_hours",
    "unlock_count",
    "app_launch_count",
    "notifications_today",
    "social_app_ratio",
    "calls_per_day",
    "call_duration_minutes",
    "unique_contacts",
    "conversation_frequency",
    "daily_displacement_km",
    "location_entropy",
    "home_time_ratio",
    "wake_time_hour",
    "sleep_time_hour",
    "sleep_duration_hours",
    "daily_step_count",
    "active_minutes",
    "keystroke_speed",
    "backspace_ratio",
    "scroll_velocity",
    "daylight_exposure_minutes",
    "charge_regularity",
    "charge_duration_hours",
    "upi_transactions_today",
    "app_uninstalls_today",
    "app_installs_today",
    "media_count_today",
    "downloads_today",
    "music_time_minutes",
]

# ── 2. Population Norms (healthy baseline) ──────────────────────────────
# CALIBRATED from StudentLife healthy cohort and literature references.
# Each entry: {"mean": float, "std": float}  (healthy population reference)
POPULATION_NORMS: Dict[str, Dict[str, float]] = {
    "screen_time_hours":          {"mean": 11.3,  "std": 1.3},
    "unlock_count":               {"mean": 3.6,   "std": 1.5},
    "app_launch_count":           {"mean": 45.0,  "std": 12.0},
    "notifications_today":        {"mean": 25.0,  "std": 8.0},
    "social_app_ratio":           {"mean": 0.08,  "std": 0.05},
    "calls_per_day":              {"mean": 31.8,  "std": 1.8},
    "call_duration_minutes":      {"mean": 15.0,  "std": 5.0},
    "unique_contacts":            {"mean": 7.2,   "std": 3.5},
    "conversation_frequency":     {"mean": 28.4,  "std": 2.5},
    "daily_displacement_km":      {"mean": 11.0,  "std": 2.0},
    "location_entropy":           {"mean": 1.5,   "std": 0.7},
    "home_time_ratio":            {"mean": 0.52,  "std": 0.12},
    "wake_time_hour":             {"mean": 6.5,   "std": 1.0},
    "sleep_time_hour":            {"mean": 10.9,  "std": 1.0},
    "sleep_duration_hours":       {"mean": 5.8,   "std": 0.9},
    "daily_step_count":           {"mean": 6000.0, "std": 1500.0},
    "active_minutes":             {"mean": 45.0,  "std": 15.0},
    "keystroke_speed":            {"mean": 3.5,   "std": 0.8},
    "backspace_ratio":            {"mean": 0.08,  "std": 0.03},
    "scroll_velocity":            {"mean": 250.0, "std": 50.0},
    "daylight_exposure_minutes":  {"mean": 60.0,  "std": 20.0},
    "charge_regularity":          {"mean": 0.85,  "std": 0.10},
    "charge_duration_hours":      {"mean": 6.2,   "std": 1.0},
    "upi_transactions_today":     {"mean": 1.5,   "std": 0.8},
    "app_uninstalls_today":       {"mean": 0.2,   "std": 0.1},
    "app_installs_today":         {"mean": 0.3,   "std": 0.1},
    "media_count_today":          {"mean": 3.0,   "std": 1.5},
    "downloads_today":            {"mean": 0.5,   "std": 0.3},
    "music_time_minutes":         {"mean": 45.0,  "std": 15.0},
}

# Expected week-over-week drift for healthy individuals (used by Gate 2).
# Represents the normal SD of weekly means across a 3-week window.
POPULATION_EXPECTED_DRIFT: Dict[str, float] = {
    "screen_time_hours":          0.4,
    "unlock_count":               6.0,
    "app_launch_count":           5.0,
    "notifications_today":        4.0,
    "social_app_ratio":           0.03,
    "calls_per_day":              0.6,
    "call_duration_minutes":      1.5,
    "unique_contacts":            1.2,
    "conversation_frequency":     0.8,
    "daily_displacement_km":      0.8,
    "location_entropy":           0.2,
    "home_time_ratio":            0.04,
    "wake_time_hour":             0.3,
    "sleep_time_hour":            0.3,
    "sleep_duration_hours":       0.3,
    "daily_step_count":           500.0,
    "active_minutes":             5.0,
    "keystroke_speed":            0.2,
    "backspace_ratio":            0.01,
    "scroll_velocity":            20.0,
    "daylight_exposure_minutes":  5.0,
    "charge_regularity":          0.05,
    "charge_duration_hours":      0.3,
    "upi_transactions_today":     0.2,
    "app_uninstalls_today":       0.1,
    "app_installs_today":         0.1,
    "media_count_today":          0.5,
    "downloads_today":            0.1,
    "music_time_minutes":         5.0,
}

# ── 3. Disorder Prototypes — Frame 1 (Absolute Values) ─────────────────
# Population-anchored.  Used during baseline screening (Days 1-28).
# Sources: StudentLife high-PHQ-9, schizophrenia dataset, DSM-5 + literature.
DISORDER_PROTOTYPES_FRAME1: Dict[str, Dict[str, float]] = {
    "healthy": {
        "screen_time_hours": 11.33,
        "unlock_count": 3.58,
        "app_launch_count": 45.0,
        "notifications_today": 25.0,
        "social_app_ratio": 0.08,
        "calls_per_day": 31.75,
        "call_duration_minutes": 15.0,
        "unique_contacts": 7.15,
        "conversation_frequency": 28.38,
        "daily_displacement_km": 11.03,
        "location_entropy": 1.51,
        "home_time_ratio": 0.52,
        "wake_time_hour": 6.47,
        "sleep_time_hour": 10.86,
        "sleep_duration_hours": 5.80,
        "daily_step_count": 6000.0,
        "active_minutes": 45.0,
        "keystroke_speed": 3.5,
        "backspace_ratio": 0.08,
        "scroll_velocity": 250.0,
        "daylight_exposure_minutes": 60.0,
        "charge_regularity": 0.85,
        "charge_duration_hours": 6.19,
        "upi_transactions_today": 1.5,
        "app_uninstalls_today": 0.2,
        "app_installs_today": 0.3,
        "media_count_today": 3.0,
        "downloads_today": 0.5,
        "music_time_minutes": 45.0,
    },
    "depression_insomnia": {
        "screen_time_hours": 12.06,
        "unlock_count": 3.91,
        "app_launch_count": 40.0,
        "notifications_today": 20.0,
        "social_app_ratio": 0.07,
        "calls_per_day": 18.47,
        "call_duration_minutes": 5.0,
        "unique_contacts": 1.81,
        "conversation_frequency": 21.97,
        "daily_displacement_km": 6.43,
        "location_entropy": 1.32,
        "home_time_ratio": 0.65,
        "wake_time_hour": 5.22,
        "sleep_time_hour": 10.73,
        "sleep_duration_hours": 4.0,
        "daily_step_count": 2500.0,
        "active_minutes": 15.0,
        "keystroke_speed": 2.2,
        "backspace_ratio": 0.16,
        "scroll_velocity": 150.0,
        "daylight_exposure_minutes": 15.0,
        "charge_regularity": 0.60,
        "charge_duration_hours": 6.89,
        "upi_transactions_today": 0.5,
        "app_uninstalls_today": 0.1,
        "app_installs_today": 0.1,
        "media_count_today": 1.0,
        "downloads_today": 0.2,
        "music_time_minutes": 15.0,
    },
    "depression_hypersomnia": {
        "screen_time_hours": 12.06,
        "unlock_count": 3.91,
        "app_launch_count": 40.0,
        "notifications_today": 20.0,
        "social_app_ratio": 0.07,
        "calls_per_day": 18.47,
        "call_duration_minutes": 5.0,
        "unique_contacts": 1.81,
        "conversation_frequency": 21.97,
        "daily_displacement_km": 6.43,
        "location_entropy": 1.32,
        "home_time_ratio": 0.65,
        "wake_time_hour": 9.22,
        "sleep_time_hour": 10.73,
        "sleep_duration_hours": 10.0,
        "daily_step_count": 2000.0,
        "active_minutes": 10.0,
        "keystroke_speed": 2.0,
        "backspace_ratio": 0.18,
        "scroll_velocity": 130.0,
        "daylight_exposure_minutes": 10.0,
        "charge_regularity": 0.55,
        "charge_duration_hours": 6.89,
        "upi_transactions_today": 0.5,
        "app_uninstalls_today": 0.1,
        "app_installs_today": 0.1,
        "media_count_today": 1.0,
        "downloads_today": 0.2,
        "music_time_minutes": 15.0,
    },
    "schizophrenia": {
        "screen_time_hours": 2.97,
        "unlock_count": 57.2,
        "app_launch_count": 25.0,
        "notifications_today": 45.0,
        "social_app_ratio": 0.48,
        "calls_per_day": 7.2,
        "call_duration_minutes": 3.0,
        "unique_contacts": 7.2,
        "conversation_frequency": 20.0,
        "daily_displacement_km": 3.5,
        "location_entropy": 1.0,
        "home_time_ratio": 0.75,
        "wake_time_hour": 2.2,
        "sleep_time_hour": 0.3,
        "sleep_duration_hours": 9.0,
        "daily_step_count": 1500.0,
        "active_minutes": 8.0,
        "keystroke_speed": 1.8,
        "backspace_ratio": 0.22,
        "scroll_velocity": 380.0,
        "daylight_exposure_minutes": 5.0,
        "charge_regularity": 0.40,
        "charge_duration_hours": 6.2,
        "upi_transactions_today": 0.2,
        "app_uninstalls_today": 0.4,
        "app_installs_today": 0.5,
        "media_count_today": 0.5,
        "downloads_today": 0.2,
        "music_time_minutes": 5.0,
    },
    "bpd": {
        "screen_time_hours": 5.0,
        "unlock_count": 70.0,
        "app_launch_count": 60.0,
        "notifications_today": 55.0,
        "social_app_ratio": 0.30,
        "calls_per_day": 5.0,
        "call_duration_minutes": 10.0,
        "unique_contacts": 6.0,
        "conversation_frequency": 4.0,
        "daily_displacement_km": 4.0,
        "location_entropy": 2.5,
        "home_time_ratio": 0.55,
        "wake_time_hour": 8.0,
        "sleep_time_hour": 0.5,
        "sleep_duration_hours": 6.0,
        "daily_step_count": 4000.0,
        "active_minutes": 25.0,
        "keystroke_speed": 4.2,
        "backspace_ratio": 0.14,
        "scroll_velocity": 320.0,
        "daylight_exposure_minutes": 35.0,
        "charge_regularity": 0.65,
        "charge_duration_hours": 3.5,
        "upi_transactions_today": 2.0,
        "app_uninstalls_today": 0.5,
        "app_installs_today": 0.6,
        "media_count_today": 4.0,
        "downloads_today": 1.0,
        "music_time_minutes": 60.0,
    },
    "bipolar_depressive": {
        "screen_time_hours": 5.0,
        "unlock_count": 28.0,
        "app_launch_count": 20.0,
        "notifications_today": 15.0,
        "social_app_ratio": 0.09,
        "calls_per_day": 1.2,
        "call_duration_minutes": 1.0,
        "unique_contacts": 2.5,
        "conversation_frequency": 1.0,
        "daily_displacement_km": 1.5,
        "location_entropy": 1.0,
        "home_time_ratio": 0.85,
        "wake_time_hour": 10.0,
        "sleep_time_hour": 1.5,
        "sleep_duration_hours": 9.0,
        "daily_step_count": 1200.0,
        "active_minutes": 5.0,
        "keystroke_speed": 1.8,
        "backspace_ratio": 0.15,
        "scroll_velocity": 120.0,
        "daylight_exposure_minutes": 10.0,
        "charge_regularity": 0.50,
        "charge_duration_hours": 5.0,
        "upi_transactions_today": 0.3,
        "app_uninstalls_today": 0.1,
        "app_installs_today": 0.1,
        "media_count_today": 0.5,
        "downloads_today": 0.1,
        "music_time_minutes": 10.0,
    },
    "bipolar_manic": {
        "screen_time_hours": 7.5,
        "unlock_count": 110.0,
        "app_launch_count": 95.0,
        "notifications_today": 65.0,
        "social_app_ratio": 0.55,
        "calls_per_day": 8.0,
        "call_duration_minutes": 25.0,
        "unique_contacts": 15.0,
        "conversation_frequency": 12.0,
        "daily_displacement_km": 7.0,
        "location_entropy": 3.8,
        "home_time_ratio": 0.25,
        "wake_time_hour": 5.0,
        "sleep_time_hour": 2.0,
        "sleep_duration_hours": 3.5,
        "daily_step_count": 12000.0,
        "active_minutes": 120.0,
        "keystroke_speed": 5.2,
        "backspace_ratio": 0.16,
        "scroll_velocity": 450.0,
        "daylight_exposure_minutes": 150.0,
        "charge_regularity": 0.30,
        "charge_duration_hours": 1.5,
        "upi_transactions_today": 4.5,
        "app_uninstalls_today": 0.8,
        "app_installs_today": 1.2,
        "media_count_today": 8.0,
        "downloads_today": 2.5,
        "music_time_minutes": 120.0,
    },
    "anxiety": {
        "screen_time_hours": 5.2,
        "unlock_count": 75.0,
        "app_launch_count": 55.0,
        "notifications_today": 45.0,
        "social_app_ratio": 0.18,
        "calls_per_day": 2.0,
        "call_duration_minutes": 8.0,
        "unique_contacts": 5.0,
        "conversation_frequency": 3.0,
        "daily_displacement_km": 2.1,
        "location_entropy": 1.8,
        "home_time_ratio": 0.72,
        "wake_time_hour": 6.5,
        "sleep_time_hour": 0.0,
        "sleep_duration_hours": 5.8,
        "daily_step_count": 3500.0,
        "active_minutes": 20.0,
        "keystroke_speed": 4.5,
        "backspace_ratio": 0.12,
        "scroll_velocity": 310.0,
        "daylight_exposure_minutes": 40.0,
        "charge_regularity": 0.70,
        "charge_duration_hours": 3.5,
        "upi_transactions_today": 1.8,
        "app_uninstalls_today": 0.2,
        "app_installs_today": 0.4,
        "media_count_today": 3.0,
        "downloads_today": 1.0,
        "music_time_minutes": 30.0,
    },
}

# ── 4. Disorder Prototypes — Frame 2 (Z-Scores from Clean Baseline) ────
# Personal-baseline-anchored.  Used during ongoing monitoring (Day 28+).
# Values = expected standard deviations from the user's verified-clean baseline.
DISORDER_PROTOTYPES_FRAME2: Dict[str, Dict[str, float]] = {
    "healthy": {f: 0.0 for f in BEHAVIORAL_FEATURES},
    # --- DEPRESSION SUBTYPES ---
    "depression_type_1": {
        "screen_time_hours": -0.60,
        "unlock_count": -0.42,
        "app_launch_count": -0.50,
        "notifications_today": -0.40,
        "social_app_ratio": -0.03,
        "calls_per_day": -1.23,
        "call_duration_minutes": -1.10,
        "unique_contacts": -0.11,
        "conversation_frequency": -0.81,
        "daily_displacement_km": -0.43,
        "location_entropy": -0.80,
        "home_time_ratio": 1.50,
        "wake_time_hour": 1.80,
        "sleep_time_hour": 1.20,
        "sleep_duration_hours": -0.87,
        "daily_step_count": -1.50,
        "active_minutes": -1.20,
        "keystroke_speed": -1.20,
        "backspace_ratio": 1.50,
        "scroll_velocity": -1.00,
        "daylight_exposure_minutes": -1.80,
        "charge_regularity": -1.20,
        "charge_duration_hours": 0.50,
        "upi_transactions_today": -0.80,
        "app_uninstalls_today": -0.50,
        "app_installs_today": -0.50,
        "media_count_today": -0.80,
        "downloads_today": -0.50,
        "music_time_minutes": -0.80,
    },
    "depression_type_2": {
        "screen_time_hours": 3.50,
        "unlock_count": 3.00,
        "app_launch_count": 2.50,
        "notifications_today": 1.80,
        "social_app_ratio": 2.20,
        "calls_per_day": -1.50,
        "call_duration_minutes": -1.20,
        "unique_contacts": -0.80,
        "conversation_frequency": -1.10,
        "daily_displacement_km": -1.80,
        "location_entropy": -1.50,
        "home_time_ratio": 2.20,
        "wake_time_hour": 2.50,
        "sleep_time_hour": 2.20,
        "sleep_duration_hours": 2.50,
        "daily_step_count": -2.20,
        "active_minutes": -1.80,
        "keystroke_speed": -1.50,
        "backspace_ratio": 1.80,
        "scroll_velocity": -1.40,
        "daylight_exposure_minutes": -2.20,
        "charge_regularity": -1.80,
        "charge_duration_hours": 1.50,
        "upi_transactions_today": -1.10,
        "app_uninstalls_today": -0.60,
        "app_installs_today": -0.60,
        "media_count_today": -0.90,
        "downloads_today": -0.60,
        "music_time_minutes": 1.20,
    },
    "depression_type_3": {
        "screen_time_hours": 1.50,
        "unlock_count": 2.20,
        "app_launch_count": 1.80,
        "notifications_today": 1.20,
        "social_app_ratio": 1.10,
        "calls_per_day": -0.80,
        "call_duration_minutes": -0.70,
        "unique_contacts": -0.50,
        "conversation_frequency": -0.60,
        "daily_displacement_km": -1.00,
        "location_entropy": -0.80,
        "home_time_ratio": 1.10,
        "wake_time_hour": 1.20,
        "sleep_time_hour": 1.10,
        "sleep_duration_hours": -1.20,
        "daily_step_count": -1.10,
        "active_minutes": -1.00,
        "keystroke_speed": 1.50,
        "backspace_ratio": 2.20,
        "scroll_velocity": 1.40,
        "daylight_exposure_minutes": -1.20,
        "charge_regularity": -1.50,
        "charge_duration_hours": 0.80,
        "upi_transactions_today": -0.60,
        "app_uninstalls_today": -0.30,
        "app_installs_today": -0.30,
        "media_count_today": -0.50,
        "downloads_today": -0.30,
        "music_time_minutes": -0.40,
    },

    # --- SCHIZOPHRENIA SUBTYPES ---
    "schizophrenia_type_1": {
        "screen_time_hours": -1.50,
        "unlock_count": -0.80,
        "app_launch_count": -1.20,
        "notifications_today": -0.60,
        "social_app_ratio": -0.80,
        "calls_per_day": -2.20,
        "call_duration_minutes": -1.80,
        "unique_contacts": -1.50,
        "conversation_frequency": -1.80,
        "daily_displacement_km": -2.50,
        "location_entropy": -2.20,
        "home_time_ratio": 3.00,
        "wake_time_hour": 2.80,
        "sleep_time_hour": 2.20,
        "sleep_duration_hours": 1.80,
        "daily_step_count": -2.80,
        "active_minutes": -2.50,
        "keystroke_speed": -2.20,
        "backspace_ratio": 2.00,
        "scroll_velocity": -1.80,
        "daylight_exposure_minutes": -2.80,
        "charge_regularity": -2.50,
        "charge_duration_hours": 1.20,
        "upi_transactions_today": -1.50,
        "app_uninstalls_today": -0.80,
        "app_installs_today": -0.80,
        "media_count_today": -1.20,
        "downloads_today": -0.80,
        "music_time_minutes": -1.50,
    },
    "schizophrenia_type_2": {
        "screen_time_hours": 4.01,
        "unlock_count": 4.83,
        "app_launch_count": 3.80,
        "notifications_today": 3.20,
        "social_app_ratio": 3.24,
        "calls_per_day": -1.10,
        "call_duration_minutes": -1.00,
        "unique_contacts": -0.90,
        "conversation_frequency": -0.80,
        "daily_displacement_km": -1.80,
        "location_entropy": -1.50,
        "home_time_ratio": 1.80,
        "wake_time_hour": -2.21,
        "sleep_time_hour": 2.80,
        "sleep_duration_hours": -1.50,
        "daily_step_count": -1.67,
        "active_minutes": -1.50,
        "keystroke_speed": 2.50,
        "backspace_ratio": 2.80,
        "scroll_velocity": 3.25,
        "daylight_exposure_minutes": -2.20,
        "charge_regularity": -2.50,
        "charge_duration_hours": 0.80,
        "upi_transactions_today": -1.10,
        "app_uninstalls_today": 1.50,
        "app_installs_today": 1.80,
        "media_count_today": -0.80,
        "downloads_today": 1.20,
        "music_time_minutes": 2.20,
    },
    "schizophrenia_type_3": {
        "screen_time_hours": 2.80,
        "unlock_count": 2.49,
        "app_launch_count": 2.10,
        "notifications_today": 1.80,
        "social_app_ratio": 1.14,
        "calls_per_day": -1.50,
        "call_duration_minutes": -1.20,
        "unique_contacts": -1.10,
        "conversation_frequency": -1.20,
        "daily_displacement_km": -2.20,
        "location_entropy": -1.80,
        "home_time_ratio": 2.50,
        "wake_time_hour": 3.00,
        "sleep_time_hour": 2.50,
        "sleep_duration_hours": 2.80,
        "daily_step_count": -2.60,
        "active_minutes": -2.20,
        "keystroke_speed": -2.50,
        "backspace_ratio": 3.20,
        "scroll_velocity": -2.20,
        "daylight_exposure_minutes": -2.80,
        "charge_regularity": -2.80,
        "charge_duration_hours": 1.10,
        "upi_transactions_today": -1.20,
        "app_uninstalls_today": -0.60,
        "app_installs_today": -0.60,
        "media_count_today": -0.80,
        "downloads_today": -0.60,
        "music_time_minutes": -1.10,
    },

    # --- HEALTHY SUBTYPES ---
    "healthy_type_1": {
        "screen_time_hours": 0.75,
        "unlock_count": 1.42,
        "app_launch_count": 1.10,
        "notifications_today": 0.80,
        "social_app_ratio": 0.80,
        "calls_per_day": 0.49,
        "call_duration_minutes": 0.60,
        "unique_contacts": 0.53,
        "conversation_frequency": 0.05,
        "daily_displacement_km": 0.17,
        "location_entropy": 1.60,
        "home_time_ratio": -0.20,
        "wake_time_hour": -0.13,
        "sleep_time_hour": 0.16,
        "sleep_duration_hours": 0.29,
        "daily_step_count": 1.20,
        "active_minutes": 1.10,
        "keystroke_speed": 0.50,
        "backspace_ratio": -0.30,
        "scroll_velocity": 0.60,
        "daylight_exposure_minutes": 0.80,
        "charge_regularity": 0.90,
        "charge_duration_hours": -0.20,
        "upi_transactions_today": 0.40,
        "app_uninstalls_today": -0.10,
        "app_installs_today": 0.10,
        "media_count_today": 0.60,
        "downloads_today": -0.20,
        "music_time_minutes": 0.50,
    },
    "healthy_type_2": {
        "screen_time_hours": 2.57,
        "unlock_count": 3.49,
        "app_launch_count": 2.80,
        "notifications_today": 2.10,
        "social_app_ratio": 2.98,
        "calls_per_day": 0.27,
        "call_duration_minutes": 0.40,
        "unique_contacts": 0.27,
        "conversation_frequency": 4.69,
        "daily_displacement_km": 0.87,
        "location_entropy": 1.73,
        "home_time_ratio": -0.10,
        "wake_time_hour": -1.00,
        "sleep_time_hour": 1.82,
        "sleep_duration_hours": 0.63,
        "daily_step_count": 1.80,
        "active_minutes": 1.50,
        "keystroke_speed": 1.10,
        "backspace_ratio": -0.40,
        "scroll_velocity": 1.50,
        "daylight_exposure_minutes": 1.20,
        "charge_regularity": 0.80,
        "charge_duration_hours": -0.10,
        "upi_transactions_today": 0.80,
        "app_uninstalls_today": 0.20,
        "app_installs_today": 0.30,
        "media_count_today": 1.20,
        "downloads_today": 0.40,
        "music_time_minutes": 1.50,
    },
    "healthy_type_3": {
        "screen_time_hours": -0.43,
        "unlock_count": -0.48,
        "app_launch_count": -0.30,
        "notifications_today": -0.20,
        "social_app_ratio": 0.21,
        "calls_per_day": -1.15,
        "call_duration_minutes": -0.80,
        "unique_contacts": -0.12,
        "conversation_frequency": -0.15,
        "daily_displacement_km": -0.40,
        "location_entropy": -0.35,
        "home_time_ratio": 0.10,
        "wake_time_hour": 0.04,
        "sleep_time_hour": 0.05,
        "sleep_duration_hours": 0.10,
        "daily_step_count": 0.20,
        "active_minutes": 0.10,
        "keystroke_speed": -0.10,
        "backspace_ratio": -0.10,
        "scroll_velocity": -0.20,
        "daylight_exposure_minutes": 0.10,
        "charge_regularity": 0.30,
        "charge_duration_hours": -0.05,
        "upi_transactions_today": -0.20,
        "app_uninstalls_today": -0.10,
        "app_installs_today": -0.10,
        "media_count_today": 0.20,
        "downloads_today": -0.10,
        "music_time_minutes": -0.20,
    },
}

# ── 5. Feature Diagnostic Weights ──────────────────────────────────────
# CALIBRATED: weights reflect real discriminative power from StudentLife.
# Higher weight = larger real z-score difference (depressed vs healthy).
# Range [0, 1].  Used in Weighted Euclidean distance (Phase 2).
FEATURE_WEIGHTS: Dict[str, float] = {
    "screen_time_hours":          0.5,
    "unlock_count":               0.2,
    "app_launch_count":           0.3,
    "notifications_today":        0.2,
    "social_app_ratio":           0.1,
    "calls_per_day":              0.6,
    "call_duration_minutes":      0.5,
    "unique_contacts":            0.5,
    "conversation_frequency":     0.9,
    "daily_displacement_km":      0.9,
    "location_entropy":           0.4,
    "home_time_ratio":            0.7,
    "wake_time_hour":             0.7,
    "sleep_time_hour":            0.1,
    "sleep_duration_hours":       0.1,
    "daily_step_count":           0.8,
    "active_minutes":             0.6,
    "keystroke_speed":            0.7,
    "backspace_ratio":            0.6,
    "scroll_velocity":            0.5,
    "daylight_exposure_minutes":  0.5,
    "charge_regularity":          0.6,
    "charge_duration_hours":      0.3,
    "upi_transactions_today":     0.4,
    "app_uninstalls_today":       0.2,
    "app_installs_today":         0.2,
    "media_count_today":          0.2,
    "downloads_today":            0.1,
    "music_time_minutes":         0.3,
}

# ── 6. Confidence Thresholds ───────────────────────────────────────────
CONFIDENCE_THRESHOLDS = {
    "high":          0.75,   # ≥ 0.75 → high-confidence classification
    "low":           0.55,   # 0.55–0.75 → "Possible [X]"
    "unclassified":  0.55,   # < 0.55 → "Unclassified — escalate"
}

# ── 7. Gate Screening Parameters ──────────────────────────────────────
GATE_PARAMS = {
    "gate1_z_threshold":       2.5,   # population z-score threshold
    "gate1_min_features":      3,     # features that must exceed threshold
    "gate1_stable_cv_threshold": 0.15,  # CV below this = stable baseline
    "gate1_stable_wide_z":     4.0,   # wider z-threshold for stable features
    "gate2_drift_multiplier":  1.5,   # drift must be > N× expected
    "gate2_min_features":      3,
    "gate3_healthy_threshold": 0.60,  # confidence above which flag (lowered from 0.65 for anxiety detection)
}

# ── 8. Temporal Shape Detection Parameters ─────────────────────────────
TEMPORAL_SHAPES = {
    "monotonic_drift": {
        "min_slope": -0.02,       # linear regression slope
        "min_r_squared": 0.6,
    },
    "oscillating": {
        "autocorr_lag_min": 3,    # days
        "autocorr_lag_max": 10,
        "autocorr_threshold": 0.4,
    },
    "chaotic": {
        "min_variance_ratio": 2.0,   # vs population expected
        "max_autocorr": 0.2,
    },
    "episodic_spike": {
        "spike_sd_threshold": 2.0,
        "recovery_window_days": 14,
    },
    "phase_flip": {
        "diff_sd_threshold": 3.0,    # between consecutive weeks
    },
}

# ── 9. Shape–Disorder Compatibility Matrix ─────────────────────────────
# Values: +1 = supports,  0 = neutral,  -1 = contradicts.
# Covers BOTH parent disorder names AND all Frame 2 subtype names so that
# temporal boost/downgrade fires correctly for every classification output.
_DEP = 1    # supports depression pattern
_SCHZ = 1   # supports schizophrenia pattern
SHAPE_DISORDER_MATRIX: Dict[str, Dict[str, int]] = {
    "monotonic_drift": {
        # parent names (Frame 1)
        "healthy": -1, "depression": 1, "schizophrenia": 0,
        "bpd": -1, "bipolar_depressive": 1, "bipolar_manic": -1, "anxiety": 0,
        # Frame 2 subtypes
        "healthy_type_1": -1, "healthy_type_2": -1, "healthy_type_3": -1,
        "depression_type_1": 1, "depression_type_2": 1, "depression_type_3": 1,
        "schizophrenia_type_1": 0, "schizophrenia_type_2": 0, "schizophrenia_type_3": 0,
    },
    "oscillating": {
        "healthy": -1, "depression": -1, "schizophrenia": 0,
        "bpd": 1, "bipolar_depressive": -1, "bipolar_manic": 0, "anxiety": 0,
        "healthy_type_1": -1, "healthy_type_2": -1, "healthy_type_3": -1,
        "depression_type_1": -1, "depression_type_2": -1, "depression_type_3": -1,
        "schizophrenia_type_1": 0, "schizophrenia_type_2": 0, "schizophrenia_type_3": 0,
    },
    "chaotic": {
        "healthy": -1, "depression": -1, "schizophrenia": 1,
        "bpd": 0, "bipolar_depressive": -1, "bipolar_manic": 0, "anxiety": 0,
        "healthy_type_1": -1, "healthy_type_2": -1, "healthy_type_3": -1,
        "depression_type_1": -1, "depression_type_2": -1, "depression_type_3": -1,
        "schizophrenia_type_1": 1, "schizophrenia_type_2": 1, "schizophrenia_type_3": 1,
    },
    "episodic_spike": {
        "healthy": 0, "depression": -1, "schizophrenia": -1,
        "bpd": 0, "bipolar_depressive": -1, "bipolar_manic": 0, "anxiety": 1,
        "healthy_type_1": 0, "healthy_type_2": 0, "healthy_type_3": 0,
        "depression_type_1": -1, "depression_type_2": -1, "depression_type_3": -1,
        "schizophrenia_type_1": -1, "schizophrenia_type_2": -1, "schizophrenia_type_3": -1,
    },
    "phase_flip": {
        "healthy": -1, "depression": -1, "schizophrenia": 0,
        "bpd": 0, "bipolar_depressive": 0, "bipolar_manic": 1, "anxiety": -1,
        "healthy_type_1": -1, "healthy_type_2": -1, "healthy_type_3": -1,
        "depression_type_1": -1, "depression_type_2": -1, "depression_type_3": -1,
        "schizophrenia_type_1": 0, "schizophrenia_type_2": 0, "schizophrenia_type_3": 0,
    },
}

# ── 10. Confidence Adjustment Factors ──────────────────────────────────
TEMPORAL_BOOST  = 1.2     # multiply when shape confirms
TEMPORAL_DOWNGRADE = 0.6  # multiply when shape contradicts

# ── 11. Life-Event Filter Parameters ──────────────────────────────────
LIFE_EVENT_PARAMS = {
    "max_co_deviating_features": 3,     # ≤ 3 features → likely situational
                                        # raised from 2: schizophrenia often presents
                                        # as 2-3 focused deviations, not broad spread
    "self_resolve_days":         10,     # resolved within N days → dismiss
    "severity_floor_sd":         1.0,   # no feature exceeds 1.0 SD → too mild to classify
}


# ── Helper: load population norms from JSON ────────────────────────────
def load_population_norms_json(path: pathlib.Path | None = None) -> Dict:
    """Load population norms from the JSON file in data/."""
    path = path or (_DATA_DIR / "population_norms.json")
    with open(path, "r") as f:
        return json.load(f)
